development:
  adapter: postgresql
  encoding: unicode
  database: dev_sizebox
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000
  host: localhost

test:
  adapter: postgres
  database: sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgres
  database: sqlite3
  pool: 5
  timeout: 5000
